add CDNJS version badge in README.md
SamVerschueren/angular2-polyfill pull request #55
Opened 2016-12-02 05:30 UTC by pvnr0082t

This badge will show the version on CDNJS!

2016-12-03 19:01 UTC, SamVerschueren requested changes

2016-12-03 19:01 UTC, SamVerschueren commented on readme.md
> +# angular2-polyfill [![Build Status](https://travis-ci.org/SamVerschueren/angular2-polyfill.svg?branch=master)](https://travis-ci.org/SamVerschueren/angular2-polyfill)[![CDNJS](https://img.shields.io
Could you add a newline after the title? When I show multiple badges in my projects, I always show them on a separate line. Thanks!

2016-12-04 08:10 UTC, pvnr0082t commented on readme.md
> +# angular2-polyfill [![Build Status](https://travis-ci.org/SamVerschueren/angular2-polyfill.svg?branch=master)](https://travis-ci.org/SamVerschueren/angular2-polyfill)[![CDNJS](https://img.shields.io
Okay, I have fixed it. Please review it again, thanks.

2016-12-04 09:02 UTC, SamVerschueren approved these changes

2016-12-04 09:02 UTC, merged

2016-12-04 09:03 UTC, SamVerschueren commented
Thanks!